[package]
name = "nmu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
color-print = "0.3.5"
id3 = "1.7.0"
itertools = "0.11.0"
metaflac = "0.2.5"
path-absolutize = "3.1.0"
regex = "1.9.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0.107"
serde_regex = "1.1.0"
serde_yaml = "0.9"
strum = { version = "0.25.0", features = ["derive"] }
tempdir = "0.3.7"
thiserror = "1.0.44"
walkdir = "2.4.0"
